initScript("expansions/OriCS_proc_fusion.lua")
initScript("expansions/OriCS_proc_link.lua")
initScript("expansions/OriCS_proc_ritual.lua")
initScript("expansions/OriCS_proc_synchro.lua")
initScript("expansions/OriCS_proc_xyz.lua")
initScript("expansions/convert-from-core/_constant.lua")
initScript("expansions/convert-from-core/_proc_fusion.lua")
initScript("expansions/convert-from-core/_proc_link.lua")
initScript("expansions/convert-from-core/_proc_pendulum.lua")
if IREDO_COMES_TRUE==nil then
	initScript("expansions/convert-from-core/_proc_procs.lua")
end
initScript("expansions/convert-from-core/_proc_ritual.lua")
initScript("expansions/convert-from-core/_proc_synchro.lua")
initScript("expansions/convert-from-core/_proc_xyz.lua")
initScript("expansions/convert-from-core/_utility.lua")